# Generated by Django 5.1.5 on 2026-01-11 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('functionality', models.TextField()),
                ('project_type', models.CharField(choices=[('web', 'Webová aplikácia'), ('physical', 'Fyzická práca')], max_length=10)),
                ('difficulty', models.IntegerField(choices=[(1, 'Veľmi ľahká'), (2, 'Ľahká'), (3, 'Stredná'), (4, 'Ťažká'), (5, 'Veľmi ťažká')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
