# Generated by Django 5.1.5 on 2026-02-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documentation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='projects/pdfs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='school_class',
            field=models.CharField(blank=True, choices=[('4AT', '4AT'), ('4AS', '4AS'), ('4AM', '4AM'), ('4AI', '4AI'), ('4BI', '4BI'), ('4CI', '4CI'), ('4AE', '4AE')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='projectedit',
            name='documentation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='projects/pdfs/'),
        ),
        migrations.AddField(
            model_name='projectedit',
            name='school_class',
            field=models.CharField(choices=[('4AT', '4AT'), ('4AS', '4AS'), ('4AM', '4AM'), ('4AI', '4AI'), ('4BI', '4BI'), ('4CI', '4CI'), ('4AE', '4AE')], default='4AT', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='projectedit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
    ]
