# Generated by Django 5.1.5 on 2026-02-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_documentation_pdf_project_school_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.IntegerField(choices=[('Veľmi ľahká', 'Veľmi ľahká'), ('Ľahká', 'Ľahká'), ('Stredná', 'Stredná'), ('Ťažká', 'Ťažká'), ('Veľmi ťažká', 'Veľmi ťažká')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='school_class',
            field=models.CharField(blank=True, choices=[('4AT', '4AT'), ('4AS', '4AS'), ('4AM', '4AM'), ('4AI', '4AI'), ('4BI', '4BI'), ('4CI', '4CI'), ('4AE', '4AE'), ('3AT', '3AT'), ('3AS', '3AS'), ('3AM', '3AM'), ('3AI', '3AI'), ('3BI', '3BI'), ('3CI', '3CI'), ('3AE', '3AE')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='projectedit',
            name='difficulty',
            field=models.IntegerField(choices=[('Veľmi ľahká', 'Veľmi ľahká'), ('Ľahká', 'Ľahká'), ('Stredná', 'Stredná'), ('Ťažká', 'Ťažká'), ('Veľmi ťažká', 'Veľmi ťažká')]),
        ),
        migrations.AlterField(
            model_name='projectedit',
            name='school_class',
            field=models.CharField(choices=[('4AT', '4AT'), ('4AS', '4AS'), ('4AM', '4AM'), ('4AI', '4AI'), ('4BI', '4BI'), ('4CI', '4CI'), ('4AE', '4AE'), ('3AT', '3AT'), ('3AS', '3AS'), ('3AM', '3AM'), ('3AI', '3AI'), ('3BI', '3BI'), ('3CI', '3CI'), ('3AE', '3AE')], max_length=3),
        ),
    ]
