# Generated by Django 5.1.5 on 2026-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved_by_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
