# Generated by Django 5.1.5 on 2026-02-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_approved_by_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='approved_by_teacher',
        ),
    ]
