# Generated by Django 5.1.5 on 2026-02-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_project_approved_by_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.CharField(choices=[('Veľmi ľahká', 'Veľmi ľahká'), ('Ľahká', 'Ľahká'), ('Stredná', 'Stredná'), ('Ťažká', 'Ťažká'), ('Veľmi ťažká', 'Veľmi ťažká')], max_length=20),
        ),
    ]
