# Generated by Django 5.1.5 on 2026-02-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Veľmi ľahká'), (2, 'Ľahká'), (3, 'Stredná'), (4, 'Ťažká'), (5, 'Veľmi ťažká')]),
        ),
        migrations.AlterField(
            model_name='projectedit',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Veľmi ľahká'), (2, 'Ľahká'), (3, 'Stredná'), (4, 'Ťažká'), (5, 'Veľmi ťažká')]),
        ),
    ]
