# Generated by Django 5.1.5 on 2026-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
